// 초등 고학년 학습용 기본 단어 풀.
// meanings는 자동 채점 시 허용할 수 있는 대표 뜻들을 함께 저장한다.
window.MASTER_WORDS = [
  ["accept", "받아들이다, 수락하다"], ["accident", "사고"], ["across", "가로질러, 건너편에"], ["act", "행동하다, 연기하다"], ["action", "행동"],
  ["active", "활동적인"], ["actually", "실제로"], ["add", "더하다, 추가하다"], ["address", "주소"], ["adventure", "모험"],
  ["afraid", "두려워하는"], ["after", "후에, 뒤에"], ["again", "다시"], ["against", "반대하여, 맞서"], ["agree", "동의하다"],
  ["air", "공기"], ["airport", "공항"], ["alive", "살아 있는"], ["allow", "허락하다"], ["almost", "거의"],
  ["alone", "혼자"], ["along", "따라서, 함께"], ["already", "이미"], ["although", "비록 ~이지만"], ["always", "항상"],
  ["amazing", "놀라운"], ["among", "~사이에"], ["amount", "양, 금액"], ["angry", "화난"], ["animal", "동물"],
  ["another", "또 하나의"], ["answer", "대답, 대답하다"], ["anyone", "누구든지"], ["anything", "무엇이든"], ["appear", "나타나다"],
  ["apple", "사과"], ["area", "지역, 영역"], ["argue", "논쟁하다"], ["arm", "팔"], ["around", "주위에, 약"],
  ["arrive", "도착하다"], ["art", "예술"], ["ask", "묻다, 부탁하다"], ["attention", "주의, 관심"], ["autumn", "가을"],
  ["available", "이용 가능한"], ["avoid", "피하다"], ["away", "떨어져, 멀리"], ["baby", "아기"], ["back", "뒤, 돌아가다"],
  ["bad", "나쁜"], ["bag", "가방"], ["balance", "균형"], ["ball", "공"], ["bank", "은행"],
  ["base", "기초, 바닥"], ["basket", "바구니"], ["bath", "목욕"], ["beach", "해변"], ["bear", "곰"],
  ["beautiful", "아름다운"], ["because", "왜냐하면"], ["become", "~이 되다"], ["before", "전에"], ["begin", "시작하다"],
  ["behind", "뒤에"], ["believe", "믿다"], ["below", "아래에"], ["beside", "옆에"], ["best", "최고의"],
  ["better", "더 나은"], ["between", "~사이에"], ["bicycle", "자전거"], ["big", "큰"], ["bird", "새"],
  ["birthday", "생일"], ["blank", "빈칸, 빈"], ["blind", "눈이 먼"], ["blood", "피"], ["board", "판, 게시판"],
  ["boat", "배"], ["body", "몸"], ["book", "책"], ["borrow", "빌리다"], ["both", "둘 다"],
  ["bottle", "병"], ["bottom", "바닥, 맨 아래"], ["box", "상자"], ["boy", "소년"], ["brain", "뇌"],
  ["branch", "나뭇가지, 지점"], ["brave", "용감한"], ["bread", "빵"], ["break", "깨뜨리다, 쉬다"], ["breakfast", "아침 식사"],
  ["bridge", "다리"], ["bright", "밝은"], ["bring", "가져오다"], ["brother", "형제"], ["build", "짓다"],
  ["building", "건물"], ["busy", "바쁜"], ["buy", "사다"], ["cake", "케이크"], ["call", "부르다, 전화하다"],
  ["camera", "카메라"], ["camp", "야영하다, 캠프"], ["can", "~할 수 있다"], ["capital", "수도, 대문자"], ["care", "돌보다, 관심"],
  ["careful", "조심스러운"], ["carry", "나르다, 들고 가다"], ["case", "경우, 상자"], ["catch", "잡다"], ["cause", "원인, 일으키다"],
  ["center", "중심"], ["certain", "확실한, 특정한"], ["chair", "의자"], ["chance", "기회, 가능성"], ["change", "바꾸다, 변화"],
  ["cheap", "싼"], ["check", "확인하다"], ["child", "아이"], ["choose", "고르다"], ["city", "도시"],
  ["class", "수업, 학급"], ["clean", "깨끗한, 청소하다"], ["clear", "분명한, 맑은"], ["climb", "오르다"], ["clock", "시계"],
  ["close", "닫다, 가까운"], ["clothes", "옷"], ["cloud", "구름"], ["club", "동아리"], ["coat", "외투"],
  ["coffee", "커피"], ["cold", "추운, 감기"], ["collect", "모으다"], ["color", "색"], ["come", "오다"],
  ["comfortable", "편안한"], ["common", "흔한, 공통의"], ["company", "회사"], ["compare", "비교하다"], ["complete", "완성하다, 완전한"],
  ["computer", "컴퓨터"], ["condition", "상태, 조건"], ["continue", "계속하다"], ["control", "통제하다, 조절하다"], ["cook", "요리하다"],
  ["cool", "시원한, 멋진"], ["copy", "복사하다"], ["corner", "모퉁이"], ["correct", "맞는, 고치다"], ["cost", "비용, 비용이 들다"],
  ["could", "~할 수 있었다"], ["country", "나라"], ["course", "과정, 강좌"], ["cover", "덮다"], ["create", "만들다"],
  ["cross", "건너다"], ["crowd", "군중"], ["cry", "울다"], ["culture", "문화"], ["cup", "컵"],
  ["cut", "자르다"], ["dance", "춤추다"], ["danger", "위험"], ["dangerous", "위험한"], ["dark", "어두운"],
  ["date", "날짜"], ["daughter", "딸"], ["day", "날"], ["dead", "죽은"], ["deal", "다루다, 거래"],
  ["decide", "결정하다"], ["deep", "깊은"], ["delicious", "맛있는"], ["describe", "묘사하다, 설명하다"], ["desk", "책상"],
  ["different", "다른"], ["difficult", "어려운"], ["dinner", "저녁 식사"], ["direction", "방향"], ["dirty", "더러운"],
  ["discover", "발견하다"], ["discuss", "토론하다"], ["distance", "거리"], ["doctor", "의사"], ["dog", "개"],
  ["door", "문"], ["down", "아래로"], ["draw", "그리다"], ["dream", "꿈, 꿈꾸다"], ["dress", "옷, 옷을 입다"],
  ["drink", "마시다, 음료"], ["drive", "운전하다"], ["drop", "떨어뜨리다"], ["during", "~동안"], ["early", "이른, 일찍"],
  ["earth", "지구, 땅"], ["easy", "쉬운"], ["eat", "먹다"], ["education", "교육"], ["effect", "효과, 영향"],
  ["egg", "달걀"], ["either", "어느 한쪽, ~도 또한 아니다"], ["else", "그 밖의"], ["empty", "빈"], ["end", "끝, 끝나다"],
  ["energy", "에너지"], ["enjoy", "즐기다"], ["enough", "충분한"], ["enter", "들어가다"], ["environment", "환경"],
  ["especially", "특히"], ["even", "심지어"], ["evening", "저녁"], ["event", "사건, 행사"], ["ever", "언제든, 지금까지"],
  ["every", "모든"], ["everyone", "모두"], ["everything", "모든 것"], ["example", "예"], ["excellent", "훌륭한"],
  ["except", "~을 제외하고"], ["excited", "신이 난"], ["exercise", "운동, 연습"], ["expect", "기대하다"], ["experience", "경험"],
  ["explain", "설명하다"], ["eye", "눈"], ["face", "얼굴, 마주보다"], ["fact", "사실"], ["fall", "떨어지다, 가을"],
  ["family", "가족"], ["famous", "유명한"], ["far", "먼"], ["farm", "농장"], ["fast", "빠른, 빨리"],
  ["father", "아버지"], ["feel", "느끼다"], ["few", "조금의"], ["field", "들판, 분야"], ["fight", "싸우다"],
  ["fill", "채우다"], ["final", "마지막의"], ["find", "찾다"], ["fine", "좋은, 괜찮은"], ["finish", "끝내다"],
  ["fire", "불"], ["first", "첫 번째의"], ["fish", "물고기"], ["floor", "바닥, 층"], ["flower", "꽃"],
  ["fly", "날다"], ["follow", "따라가다"], ["food", "음식"], ["foot", "발"], ["forest", "숲"],
  ["forget", "잊다"], ["free", "자유로운, 무료의"], ["fresh", "신선한"], ["friend", "친구"], ["front", "앞"],
  ["fruit", "과일"], ["full", "가득 찬"], ["fun", "재미"], ["future", "미래"], ["game", "게임, 경기"],
  ["garden", "정원"], ["get", "얻다, 받다"], ["girl", "소녀"], ["give", "주다"], ["glad", "기쁜"],
  ["glass", "유리, 잔"], ["go", "가다"], ["goal", "목표"], ["good", "좋은"], ["grade", "학년, 성적"],
  ["great", "훌륭한, 큰"], ["green", "초록색"], ["ground", "땅"], ["group", "무리, 그룹"], ["grow", "자라다"],
  ["guess", "추측하다"], ["guide", "안내하다, 안내자"], ["happen", "일어나다"], ["happy", "행복한"], ["hard", "어려운, 열심히"],
  ["have", "가지다"], ["head", "머리"], ["health", "건강"], ["hear", "듣다"], ["heart", "심장, 마음"],
  ["heavy", "무거운"], ["help", "돕다"], ["here", "여기에"], ["high", "높은"], ["hill", "언덕"],
  ["history", "역사"], ["hold", "잡다, 개최하다"], ["holiday", "휴일"], ["home", "집"], ["hope", "바라다, 희망"],
  ["hospital", "병원"], ["hot", "뜨거운"], ["hotel", "호텔"], ["hour", "시간"], ["house", "집"],
  ["however", "하지만, 그러나"], ["huge", "거대한"], ["human", "인간"], ["hungry", "배고픈"], ["hurry", "서두르다"],
  ["idea", "생각, 아이디어"], ["important", "중요한"], ["improve", "향상시키다"], ["include", "포함하다"], ["information", "정보"],
  ["inside", "안쪽에"], ["instead", "대신에"], ["interesting", "흥미로운"], ["introduce", "소개하다"], ["invite", "초대하다"],
  ["island", "섬"], ["job", "직업, 일"], ["join", "참여하다, 가입하다"], ["journey", "여행"], ["jump", "뛰다"],
  ["keep", "유지하다, 보관하다"], ["key", "열쇠, 핵심"], ["kind", "친절한, 종류"], ["kitchen", "부엌"], ["know", "알다"],
  ["lake", "호수"], ["language", "언어"], ["large", "큰"], ["last", "마지막의, 지속되다"], ["late", "늦은"],
  ["later", "나중에"], ["laugh", "웃다"], ["learn", "배우다"], ["leave", "떠나다, 남기다"], ["left", "왼쪽의"],
  ["lesson", "수업"], ["letter", "편지, 글자"], ["library", "도서관"], ["life", "삶, 생명"], ["light", "빛, 가벼운"],
  ["like", "좋아하다, ~처럼"], ["line", "줄, 선"], ["listen", "듣다"], ["little", "작은, 조금"], ["live", "살다"],
  ["local", "지역의"], ["long", "긴"], ["look", "보다"], ["lose", "잃다, 지다"], ["loud", "시끄러운"],
  ["love", "사랑하다"], ["lucky", "운이 좋은"], ["lunch", "점심 식사"], ["machine", "기계"], ["main", "주요한"],
  ["make", "만들다"], ["many", "많은"], ["map", "지도"], ["market", "시장"], ["matter", "문제, 중요하다"],
  ["maybe", "아마"], ["meal", "식사"], ["mean", "의미하다"], ["meet", "만나다"], ["member", "구성원"],
  ["message", "메시지"], ["middle", "가운데"], ["minute", "분"], ["miss", "놓치다, 그리워하다"], ["model", "모형, 모델"],
  ["money", "돈"], ["month", "달, 월"], ["moon", "달"], ["more", "더 많은"], ["morning", "아침"],
  ["most", "대부분, 가장"], ["mother", "어머니"], ["mountain", "산"], ["mouth", "입"], ["move", "움직이다"],
  ["movie", "영화"], ["much", "많은"], ["music", "음악"], ["must", "~해야 한다"], ["name", "이름"],
  ["nature", "자연"], ["near", "가까운"], ["necessary", "필요한"], ["need", "필요하다"], ["never", "결코 ~않다"],
  ["new", "새로운"], ["next", "다음의"], ["night", "밤"], ["noise", "소음"], ["north", "북쪽"],
  ["nothing", "아무것도 없음"], ["notice", "알아차리다, 공지"], ["number", "숫자"], ["often", "자주"], ["old", "늙은, 오래된"],
  ["once", "한 번"], ["only", "오직"], ["open", "열다, 열린"], ["opinion", "의견"], ["opposite", "반대의"],
  ["order", "순서, 주문하다"], ["other", "다른"], ["outside", "밖에"], ["over", "위에, 끝난"], ["own", "자신의, 소유하다"],
  ["page", "페이지"], ["paint", "칠하다, 그리다"], ["paper", "종이"], ["parent", "부모"], ["park", "공원"],
  ["part", "부분"], ["party", "파티"], ["pass", "지나가다, 통과하다"], ["past", "과거, 지난"], ["pay", "지불하다"],
  ["people", "사람들"], ["perhaps", "아마도"], ["person", "사람"], ["phone", "전화"], ["photo", "사진"],
  ["pick", "고르다, 줍다"], ["picture", "그림, 사진"], ["place", "장소"], ["plan", "계획"], ["plant", "식물, 심다"],
  ["play", "놀다, 경기하다"], ["please", "제발, 기쁘게 하다"], ["point", "점, 요점"], ["popular", "인기 있는"], ["possible", "가능한"],
  ["practice", "연습, 연습하다"], ["prepare", "준비하다"], ["present", "현재의, 선물, 발표하다"], ["pretty", "예쁜, 꽤"], ["problem", "문제"],
  ["promise", "약속하다"], ["protect", "보호하다"], ["proud", "자랑스러운"], ["question", "질문"], ["quick", "빠른"],
  ["quiet", "조용한"], ["quite", "꽤"], ["rain", "비"], ["reach", "도착하다, 닿다"], ["read", "읽다"],
  ["ready", "준비된"], ["real", "진짜의"], ["really", "정말로"], ["reason", "이유"], ["receive", "받다"],
  ["remember", "기억하다"], ["repeat", "반복하다"], ["report", "보고서, 보고하다"], ["rest", "쉬다, 휴식"], ["restaurant", "식당"],
  ["result", "결과"], ["return", "돌아오다, 돌려주다"], ["rice", "쌀, 밥"], ["ride", "타다"], ["right", "오른쪽의, 맞는"],
  ["river", "강"], ["road", "길"], ["room", "방"], ["round", "둥근, 주위로"], ["run", "달리다"],
  ["safe", "안전한"], ["same", "같은"], ["save", "구하다, 저장하다, 절약하다"], ["say", "말하다"], ["school", "학교"],
  ["science", "과학"], ["sea", "바다"], ["season", "계절"], ["seat", "좌석"], ["second", "두 번째의, 초"],
  ["see", "보다"], ["seem", "~처럼 보이다"], ["sell", "팔다"], ["send", "보내다"], ["sentence", "문장"],
  ["service", "서비스"], ["set", "놓다, 세트"], ["several", "몇몇의"], ["share", "나누다, 공유하다"], ["shop", "가게, 쇼핑하다"],
  ["short", "짧은"], ["should", "~해야 한다"], ["show", "보여주다"], ["side", "쪽, 옆"], ["simple", "간단한"],
  ["since", "~이래로, 때문에"], ["sing", "노래하다"], ["sister", "자매"], ["sit", "앉다"], ["size", "크기"],
  ["skill", "기술"], ["sleep", "자다"], ["slow", "느린"], ["small", "작은"], ["smile", "미소 짓다"],
  ["snow", "눈"], ["some", "몇몇의"], ["someone", "누군가"], ["something", "무언가"], ["sometimes", "때때로"],
  ["song", "노래"], ["soon", "곧"], ["sorry", "미안한"], ["sound", "소리"], ["south", "남쪽"],
  ["space", "공간, 우주"], ["speak", "말하다"], ["special", "특별한"], ["spend", "쓰다, 보내다"], ["sport", "운동"],
  ["spring", "봄"], ["stand", "서다"], ["start", "시작하다"], ["station", "역"], ["stay", "머무르다"],
  ["still", "여전히"], ["stop", "멈추다"], ["store", "가게, 저장하다"], ["story", "이야기"], ["street", "거리"],
  ["strong", "강한"], ["student", "학생"], ["study", "공부하다"], ["subject", "과목, 주제"], ["success", "성공"],
  ["summer", "여름"], ["sun", "태양"], ["sure", "확신하는"], ["surprise", "놀라게 하다, 놀라움"], ["swim", "수영하다"],
  ["table", "탁자"], ["take", "가져가다, 취하다"], ["talk", "말하다"], ["teach", "가르치다"], ["team", "팀"],
  ["tell", "말해주다"], ["test", "시험"], ["than", "~보다"], ["thank", "감사하다"], ["then", "그때, 그러고 나서"],
  ["there", "거기에"], ["thing", "것"], ["think", "생각하다"], ["through", "통하여"], ["time", "시간"],
  ["tired", "피곤한"], ["today", "오늘"], ["together", "함께"], ["tomorrow", "내일"], ["top", "꼭대기"],
  ["town", "마을"], ["train", "기차, 훈련하다"], ["travel", "여행하다"], ["tree", "나무"], ["trip", "여행"],
  ["true", "사실인"], ["try", "시도하다"], ["turn", "돌다, 차례"], ["under", "아래에"], ["understand", "이해하다"],
  ["until", "~까지"], ["up", "위로"], ["use", "사용하다"], ["usual", "평소의"], ["usually", "보통"],
  ["vacation", "방학, 휴가"], ["vegetable", "채소"], ["very", "매우"], ["visit", "방문하다"], ["voice", "목소리"],
  ["wait", "기다리다"], ["walk", "걷다"], ["wall", "벽"], ["want", "원하다"], ["warm", "따뜻한"],
  ["wash", "씻다"], ["watch", "보다, 손목시계"], ["water", "물"], ["way", "방법, 길"], ["weather", "날씨"],
  ["week", "주"], ["welcome", "환영하다"], ["well", "잘, 건강한"], ["west", "서쪽"], ["what", "무엇"],
  ["when", "언제"], ["where", "어디에"], ["which", "어느 것"], ["while", "~동안"], ["white", "흰색의"],
  ["whole", "전체의"], ["why", "왜"], ["wide", "넓은"], ["win", "이기다"], ["wind", "바람"],
  ["window", "창문"], ["winter", "겨울"], ["wish", "바라다"], ["with", "~와 함께"], ["without", "~없이"],
  ["woman", "여자"], ["wonder", "궁금해하다"], ["word", "단어"], ["work", "일하다"], ["world", "세계"],
  ["worry", "걱정하다"], ["write", "쓰다"], ["wrong", "틀린"], ["year", "해, 년"], ["young", "어린"],
  ["above", "위에"], ["absent", "결석한, 없는"], ["achieve", "달성하다, 성취하다, 이루다"], ["advice", "조언"], ["affect", "영향을 미치다"],
  ["ancient", "고대의"], ["announce", "발표하다"], ["attend", "참석하다"], ["average", "평균"], ["behave", "행동하다"],
  ["benefit", "이익, 도움이 되다"], ["beyond", "~을 넘어"], ["breathe", "숨 쉬다"], ["cancel", "취소하다"], ["celebrate", "축하하다"],
  ["certainly", "확실히"], ["character", "성격, 등장인물"], ["communicate", "의사소통하다"], ["community", "지역사회, 공동체"], ["consider", "고려하다"],
  ["contact", "연락하다, 연락"], ["contain", "포함하다"], ["conversation", "대화"], ["decision", "결정"], ["develop", "발전시키다, 개발하다"],
  ["difference", "차이"], ["direct", "직접적인, 지시하다"], ["environmental", "환경의"], ["exact", "정확한"], ["express", "표현하다"],
  ["foreign", "외국의"], ["government", "정부"], ["habit", "습관"], ["imagine", "상상하다"], ["increase", "증가하다, 증가"],
  ["independent", "독립적인"], ["instead of", "~대신에"], ["international", "국제적인"], ["knowledge", "지식"], ["machine", "기계"],
  ["natural", "자연의"], ["normal", "정상적인, 보통의"], ["offer", "제공하다, 제안하다"], ["perform", "수행하다, 공연하다"], ["pollution", "오염"],
  ["probably", "아마도"], ["public", "공공의"], ["purpose", "목적"], ["reduce", "줄이다"], ["relationship", "관계"],
  ["respect", "존중하다, 존중"], ["responsible", "책임이 있는"], ["separate", "분리하다, 별개의"], ["similar", "비슷한"], ["situation", "상황"],
  ["solve", "해결하다"], ["support", "지원하다, 지지하다"], ["traditional", "전통적인"], ["traffic", "교통"], ["valuable", "가치 있는"],
  ["various", "다양한"], ["whisper", "속삭이다"], ["wonderful", "훌륭한, 멋진"], ["ability", "능력"], ["abroad", "해외에"],
  ["according", "~에 따르면"], ["activity", "활동"], ["adult", "성인"], ["advantage", "장점"], ["advertisement", "광고"],
  ["allowance", "용돈, 허용량"], ["appointment", "약속, 예약"], ["article", "기사, 글"], ["background", "배경"], ["behavior", "행동"],
  ["belong", "속하다"], ["calendar", "달력"], ["carefully", "조심스럽게"], ["century", "세기"], ["challenge", "도전"],
  ["choice", "선택"], ["collect", "수집하다"], ["comfortable", "편안한"], ["competition", "경쟁, 대회"], ["convenient", "편리한"],
  ["creative", "창의적인"], ["decision", "결정"], ["degree", "정도, 학위, 도"], ["depend", "의존하다"], ["detail", "세부사항"],
  ["develop", "개발하다, 발전하다"], ["disappear", "사라지다"], ["disease", "질병"], ["electricity", "전기"], ["encourage", "격려하다"],
  ["engineer", "기술자, 엔지니어"], ["especially", "특히"], ["factory", "공장"], ["favorite", "가장 좋아하는"], ["festival", "축제"],
  ["finally", "마침내"], ["general", "일반적인"], ["healthy", "건강한"], ["immediately", "즉시"], ["instead", "대신에"],
  ["interest", "관심, 흥미"], ["interview", "면접, 인터뷰"], ["invent", "발명하다"], ["local", "지역의"], ["manage", "관리하다, 해내다"],
  ["material", "재료"], ["memory", "기억"], ["method", "방법"], ["necessary", "필요한"], ["opportunity", "기회"],
  ["organization", "조직"], ["original", "원래의, 독창적인"], ["personal", "개인의"], ["prepare", "준비하다"], ["prevent", "막다, 예방하다"],
  ["project", "프로젝트"], ["provide", "제공하다"], ["recycle", "재활용하다"], ["regular", "규칙적인"], ["remember", "기억하다"],
  ["require", "요구하다, 필요로 하다"], ["research", "연구"], ["select", "선택하다"], ["serious", "심각한, 진지한"], ["society", "사회"],
  ["solution", "해결책"], ["suggest", "제안하다"], ["technology", "기술"], ["temperature", "온도"], ["transportation", "교통수단"],
  ["understanding", "이해"], ["unusual", "특이한"], ["volunteer", "자원봉사자, 자원봉사하다"], ["whether", "~인지 아닌지"], ["within", "~이내에, 안에"]
].filter(([english], index, arr) => arr.findIndex(([e]) => e === english) === index).map(([english, korean], index) => ({
  id: index + 1,
  english,
  korean,
  meanings: korean.split(/[,/]/).map(v => v.trim()).filter(Boolean)
}));
